# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_pic',
            field=models.FileField(upload_to='images/latest'),
        ),
    ]
