# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20170720_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='Description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='index_dress',
            name='Description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='index_footwear',
            name='Description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='index_jeans',
            name='Description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='index_products',
            name='Description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='index_salwar',
            name='Description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='index_sarees',
            name='Description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='index_shirts',
            name='Description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='index_skirts',
            name='Description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='index_sweaters',
            name='Description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='index_watch',
            name='Description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.CharField(max_length=2500),
        ),
    ]
